# Generated by Django 5.0.8 on 2024-12-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerhead', '0004_alter_camphead_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
