# Generated by Django 5.1.4 on 2025-01-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerhead', '0006_alter_camp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
