# Generated by Django 5.0.8 on 2024-12-25 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
        ('volunteerhead', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.AddField(
            model_name='product',
            name='camp1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='volunteerhead.camp'),
        ),
    ]
