# Generated by Django 5.0.8 on 2025-01-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_remove_product_group_product_camp1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
