# Generated by Django 5.0.8 on 2025-01-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='to',
            field=models.CharField(max_length=20),
        ),
    ]
