# Generated by Django 5.1.5 on 2025-01-29 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to',
            field=models.CharField(choices=[('Admin', 'Admin'), ('VolunteerHead', 'Volunteer Head'), ('CampHead', 'Camp Head'), ('Volunteer', 'Volunteer')], max_length=20),
        ),
    ]
