# Generated by Django 5.1.4 on 2025-03-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_user_alter_notification_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='from1',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('VolunteerHead', 'Volunteer Head'), ('CampHead', 'Camp Head'), ('Volunteer', 'Volunteer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('VolunteerHead', 'Volunteer Head'), ('CampHead', 'Camp Head'), ('Volunteer', 'Volunteer')], max_length=20, null=True),
        ),
    ]
