# Generated by Django 5.0.8 on 2024-12-25 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('volunteerhead', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camphead',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.AddField(
            model_name='camp',
            name='campHead1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campHead2', to='volunteerhead.camphead'),
        ),
        migrations.AddField(
            model_name='camphead',
            name='zone1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zone3', to='superadmin.zone'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='camp1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp2', to='volunteerhead.camp'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='zone1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zone2', to='superadmin.zone'),
        ),
    ]
