# Generated by Django 5.0.8 on 2024-12-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerhead', '0005_volunteer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
